### ISSUE TITLE
Condition to switch between day, month, year view

### ISSUE THREAD

**Issue by ashwinkumar6** [aaronoah/kibana_calendar_vis#6]
- The calendar_vis has three types of views 
  - Day view
  - Month view
  - Year view
- Currently the condition used to determine when to switch between the 3 types of views are as follows 
```
// get the difference between to and from
const diff = to.diff(from, 'days');

// render a day view
if (diff <= 1)
// render a month view
else if (diff > 1 && diff < 32 && new Date(from).getMonth() === new Date(to).getMonth())
// render a year view
else if (diff > 31)
```
There a couple or corner cases which this will not handle
- *Scenario 1* 
currentDate: 01/03/2019 12:05am  
1h from today would render a day view since `diff<1` but a year view is expected since range lies across months
- *Scenario 2* 
currentDate: 05/03/2019 12:05am  
1h from today would render a day view since `diff<1` but a month view is expected since range lies across two days

The condition should not be based on the difference between `to` and `from` instead, based on the day/month/year they lie in, such as the conditions below  
```
// render a day view 
if ( moment(new Date(from)).format("MMM Do YY") === moment(new Date(to)).format("MMM Do YY") ) 
// render a month view
else if (new Date(from).getMonth() === new Date(to).getMonth()  && new Date(from).getFullYear() === new Date(to).getFullYear())
// render a year view
else
```

**Expected Behaviour**
Condition used to determine when to switch between the 3 types of views be based on the day/month/year they lie in

**Actual Behaviour**
Condition used to determine when to switch between the 3 types of views are based on the based on the difference between `to` and `from`

**Basic Information**
kibana version: 6.4

**Comment by aaronoah** [comment]
hi @ashwinkumar6, Thanks for bringing out the issue, would you be interested in providing a fix?

**Comment by ashwinkumar6** [comment]
Sure, would be glad to. I'll raise a PR and reference it to this issue
